### ISSUE TITLE
how to insert an inline image?

### ISSUE THREAD

**Issue by Xujkstra** [surmon-china/vue-quill-editor#144]
### Versions:
+ vue-quill-editor: 3.0.4
+ vue: 2.5.13

### issue
when i invoke the quill insertEmber method, the image tag will be wrapped by a p element, is there any approach to make the image in the same line with text?

**Comment by surmon-china** [comment]
If you want to remove the p tag, this is not possible because Quill relies on it to work, but if you just want the image and text to be inside the same tag, then normal `insertEmbed` can be done.

https://quilljs.com/docs/api/#insertembed

```javascript
this.editor.insertEmbed(10, 'image', 'http://quilljs.com/images/cloud.png');
```

![image](https://user-images.githubusercontent.com/14019524/35394323-770f39a0-0222-11e8-8a14-a9495b088f70.png)

**Comment by kodeschooler** [comment]
I tried the same thing above (surmon's) and it is *not* putting the image inside the block. It wraps my text in a <p> or a <div> depending on which block I registered, and then it inserts the image, causing the image to be put on the next line. I am following another example from you guys where I import from '/blots/block/embed'. What import can I use to achieve the result shown above? All I want to do is have someone type text and then when they click a button, to insert the image at the cursor and have it appear inline with the text (unless the cursor would force it to be on next line). I have to use a custom attribute on my image too (which is why I'm subclassing BlockEmbed. I am using quill.editor.insertEmbed. Thank you for any direction. On button click, I simply want to say:

editor.pasteHTML(cursorPosition, '<img src="/img.png" abc="abc" height="15">') and have it put that after i say here: [click button]
