### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by rdgout** [surmon-china/vue-quill-editor#48]
Hi,

Using the latest version of this package.
I have an issue with the placeholder. I placed the options into a computed property and when I change the placeholder it doesn't seem to change. The options are changed when I inspect the element but it doesn't actually change the placeholder on the front-end.

My situation is that when I change languages in my edit screen, I turn the old content into the placeholder.

To illustrate what I mean:
 
![schermafbeelding 2017-05-16 om 14 38 19](https://cloud.githubusercontent.com/assets/4692202/26106216/78f2f298-3a45-11e7-865d-36424574ed1a.png)

Note the actual placeholder "Default message" and the placeholder as seen in the props.

Can you fix it so that it keeps watching the placeholder?

**Comment by shockwavemoto** [comment]
Using the latest version of this package.
I have an issue with the placeholder. I placed the options into a computed property and when I change the placeholder it doesn't seem to change. The options are changed when I inspect the element but it doesn't actually change the placeholder on the front-end.

My situation is that when I change languages in my edit screen, I turn the old content into the placeholder.: 
Note the actual placeholder "Default message" and the placeholder as seen in the props.

Can you fix it so that it keeps watching the placeholder?
:small_airplane: :small_orange_diamond:

**Comment by surmon-china** [comment]
https://github.com/quilljs/quill/issues/1443

**Comment by surmon-china** [comment]
@rdgout @shockwavemoto It will be work!

https://github.com/quilljs/quill/issues/1150

```javascript
this.quill.root.setAttribute('data-placeholder', "Your new placeholder");
```

**Comment by MarkRizun** [comment]
Hello, 

I would like to reopen this issue, as the initial problem is not solved: placeholder does not change dynamically with the change of the computed propery, i.e. placeholder is not being "watched".
For example, see: https://jsfiddle.net/yh2af91z/

Cheers,
Mark
