### ISSUE TITLE
Need help to set some tricks

### ISSUE THREAD

**Issue by marcusvbp** [surmon-china/vue-quill-editor#49]
Hi, You have a nice project!

But I need help to set some tricks:

- I want all pasted text to be in plain text
- I want all links to be converted in HTML links
- If possible, I want to translate the interface to my language

Thanks!

**Comment by shockwavemoto** [comment]
Hi, You have a nice project!

But I need help to set some tricks:

I want all pasted text to be in plain text
I want all links to be converted in HTML links
If possible, I want to translate the interface to my language
Thanks!

**Comment by surmon-china** [comment]
thank you for your support! Your needs can be achieved through the quill expansion or module, because the quill itself is an open editor, it will be more features to the developers, please look for github or google quill related modules to solve your The problem, it has nothing to do with the framework.
